"""update service models for page 2

Revision ID: 07079848dc04
Revises: 9ac79dec9f3a
Create Date: 2025-12-22 08:20:14.870271

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '07079848dc04'
down_revision: Union[str, Sequence[str], None] = '9ac79dec9f3a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service_methodologies', sa.Column('icon_image', sa.String(), nullable=True))
    op.add_column('service_pages', sa.Column('quick_step_layout', sa.String(), nullable=False, server_default='steps'))
    op.add_column('service_pages', sa.Column('methodology_layout', sa.String(), nullable=False, server_default='timeline'))
    op.add_column('service_quick_steps', sa.Column('checklist', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('service_quick_steps', 'checklist')
    op.drop_column('service_pages', 'methodology_layout')
    op.drop_column('service_pages', 'quick_step_layout')
    op.drop_column('service_methodologies', 'icon_image')
    # ### end Alembic commands ###
