"""Solution db update

Revision ID: 0f380b0f3d22
Revises: 18fb2049782e
Create Date: 2025-12-19 06:22:36.666856

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f380b0f3d22'
down_revision: Union[str, Sequence[str], None] = '18fb2049782e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('solutions', sa.Column('core_benefits_title', sa.String(), nullable=True))
    op.add_column('solutions', sa.Column('core_benefits_subtitle', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('solutions', 'core_benefits_subtitle')
    op.drop_column('solutions', 'core_benefits_title')
    # ### end Alembic commands ###
