"""add hero image and cta fields to products

Revision ID: 1290d9ad04f9
Revises: 450e04af5a2a
Create Date: 2025-12-16 16:13:19.320376

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1290d9ad04f9'
down_revision: Union[str, Sequence[str], None] = '450e04af5a2a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_features', sa.Column('image_url', sa.String(), nullable=True))
    op.add_column('products', sa.Column('hero_image', sa.String(), nullable=True))
    op.add_column('products', sa.Column('cta_primary_text', sa.String(), nullable=True))
    op.add_column('products', sa.Column('cta_secondary_text', sa.String(), nullable=True))
    op.add_column('products', sa.Column('cta_image', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'cta_image')
    op.drop_column('products', 'cta_secondary_text')
    op.drop_column('products', 'cta_primary_text')
    op.drop_column('products', 'hero_image')
    op.drop_column('product_features', 'image_url')
    # ### end Alembic commands ###
