"""revisi 2, tanpa Sqlalchemy-utils

Revision ID: 18e479cf7979
Revises: 221108470d9e
Create Date: 2025-11-28 15:58:47.856354

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '18e479cf7979'
down_revision: Union[str, Sequence[str], None] = '221108470d9e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
