"""add focus_section_tagline

Revision ID: 1ffee2ce1cae
Revises: 07079848dc04
Create Date: 2025-12-22 08:44:35.760143

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ffee2ce1cae'
down_revision: Union[str, Sequence[str], None] = '07079848dc04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service_pages', sa.Column('focus_section_tagline', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('service_pages', 'focus_section_tagline')
    # ### end Alembic commands ###
