"""update solution with hero cta and social trust

Revision ID: 2241b17a398d
Revises: 8b205f7f71ae
Create Date: 2025-12-17 14:26:34.029232

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2241b17a398d'
down_revision: Union[str, Sequence[str], None] = '8b205f7f71ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('solution_social_trust_links',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('solution_id', sa.UUID(), nullable=True),
    sa.Column('social_trust_id', sa.UUID(), nullable=True),
    sa.Column('sequence', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['social_trust_id'], ['social_trusts.id'], ),
    sa.ForeignKeyConstraint(['solution_id'], ['solutions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_solution_social_trust_links_id'), 'solution_social_trust_links', ['id'], unique=False)
    op.create_index(op.f('ix_solution_social_trust_links_sequence'), 'solution_social_trust_links', ['sequence'], unique=False)
    op.add_column('solutions', sa.Column('hero_image', sa.String(), nullable=True))
    op.add_column('solutions', sa.Column('cta_primary_text', sa.String(), nullable=True))
    op.add_column('solutions', sa.Column('cta_secondary_text', sa.String(), nullable=True))
    op.add_column('solutions', sa.Column('cta_image', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('solutions', 'cta_image')
    op.drop_column('solutions', 'cta_secondary_text')
    op.drop_column('solutions', 'cta_primary_text')
    op.drop_column('solutions', 'hero_image')
    op.drop_index(op.f('ix_solution_social_trust_links_sequence'), table_name='solution_social_trust_links')
    op.drop_index(op.f('ix_solution_social_trust_links_id'), table_name='solution_social_trust_links')
    op.drop_table('solution_social_trust_links')
    # ### end Alembic commands ###
