"""add layout_type to products

Revision ID: 31109c1691fa
Revises: 1290d9ad04f9
Create Date: 2025-12-17 08:35:03.235873

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31109c1691fa'
down_revision: Union[str, Sequence[str], None] = '1290d9ad04f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('product_features', 'tab_label',
               existing_type=sa.TEXT(),
               nullable=True)
    op.add_column('products', sa.Column('layout_type', sa.String(), nullable=False, server_default='default'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'layout_type')
    op.alter_column('product_features', 'tab_label',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
