"""Add User model and link to Author

Revision ID: 450e04af5a2a
Revises: 8297d17d6ce7
Create Date: 2025-12-16 09:18:28.097099

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '450e04af5a2a'
down_revision: Union[str, Sequence[str], None] = '8297d17d6ce7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.add_column('authors', sa.Column('user_id', sa.UUID(), nullable=True))
    op.create_unique_constraint(None, 'authors', ['user_id'])
    op.create_foreign_key(None, 'authors', 'users', ['user_id'], ['id'])
    op.drop_index(op.f('idx_products_search_concat'), table_name='products', postgresql_ops={"((((COALESCE(name, ''::text) || ' '::text) || COALESCE(hero_title, ''::text)) || ' '::text) || COALESCE(hero_subtitle, ''::text))": 'gin_trgm_ops'}, postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_products_search_concat'), 'products', [sa.literal_column("((((COALESCE(name, ''::text) || ' '::text) || COALESCE(hero_title, ''::text)) || ' '::text) || COALESCE(hero_subtitle, ''::text))")], unique=False, postgresql_ops={"((((COALESCE(name, ''::text) || ' '::text) || COALESCE(hero_title, ''::text)) || ' '::text) || COALESCE(hero_subtitle, ''::text))": 'gin_trgm_ops'}, postgresql_using='gin')
    op.drop_constraint(None, 'authors', type_='foreignkey')
    op.drop_constraint(None, 'authors', type_='unique')
    op.drop_column('authors', 'user_id')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
