"""initial_migration

Revision ID: 45a9e5e68a03
Revises: 
Create Date: 2025-12-23 09:49:40.635202

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '45a9e5e68a03'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_categories_id'), 'categories', ['id'], unique=False)
    op.create_table('products',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('slug', sa.String(), nullable=True),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('hero_title', sa.Text(), nullable=False),
    sa.Column('hero_subtitle', sa.Text(), nullable=True),
    sa.Column('hero_image', sa.String(), nullable=True),
    sa.Column('cta_primary_text', sa.String(), nullable=True),
    sa.Column('cta_secondary_text', sa.String(), nullable=True),
    sa.Column('cta_image', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('layout_type', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_category'), 'products', ['category'], unique=False)
    op.create_index(op.f('ix_products_id'), 'products', ['id'], unique=False)
    op.create_index(op.f('ix_products_slug'), 'products', ['slug'], unique=True)
    op.create_table('service_pages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('slug', sa.String(), nullable=True),
    sa.Column('page_name', sa.Text(), nullable=False),
    sa.Column('hero_heading', sa.Text(), nullable=False),
    sa.Column('hero_tagline', sa.Text(), nullable=True),
    sa.Column('hero_bg_image', sa.String(), nullable=True),
    sa.Column('focus_section_tagline', sa.Text(), nullable=True),
    sa.Column('focus_section_heading', sa.Text(), nullable=True),
    sa.Column('focus_section_desc', sa.Text(), nullable=True),
    sa.Column('quick_step_layout', sa.String(), nullable=False),
    sa.Column('quick_step_heading', sa.Text(), nullable=True),
    sa.Column('quick_step_subheading', sa.Text(), nullable=True),
    sa.Column('quick_step_footer', sa.Text(), nullable=True),
    sa.Column('offering_heading', sa.Text(), nullable=True),
    sa.Column('offering_desc', sa.Text(), nullable=True),
    sa.Column('methodology_layout', sa.String(), nullable=False),
    sa.Column('methodology_footer', sa.Text(), nullable=True),
    sa.Column('methodology_heading', sa.Text(), nullable=True),
    sa.Column('methodology_desc', sa.Text(), nullable=True),
    sa.Column('competency_footer', sa.Text(), nullable=True),
    sa.Column('competency_heading', sa.Text(), nullable=True),
    sa.Column('competency_desc', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_service_pages_id'), 'service_pages', ['id'], unique=False)
    op.create_index(op.f('ix_service_pages_slug'), 'service_pages', ['slug'], unique=True)
    op.create_table('social_trusts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('logo_url', sa.String(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_social_trusts_id'), 'social_trusts', ['id'], unique=False)
    op.create_index(op.f('ix_social_trusts_sequence'), 'social_trusts', ['sequence'], unique=False)
    op.create_table('solutions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('slug', sa.String(), nullable=True),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('hero_title', sa.Text(), nullable=False),
    sa.Column('hero_subtitle', sa.Text(), nullable=True),
    sa.Column('hero_image', sa.String(), nullable=True),
    sa.Column('cta_primary_text', sa.String(), nullable=True),
    sa.Column('cta_secondary_text', sa.String(), nullable=True),
    sa.Column('cta_image', sa.String(), nullable=True),
    sa.Column('core_benefits_title', sa.String(), nullable=True),
    sa.Column('core_benefits_subtitle', sa.Text(), nullable=True),
    sa.Column('core_solution_title', sa.String(), nullable=True),
    sa.Column('core_solution_subtitle', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_solutions_id'), 'solutions', ['id'], unique=False)
    op.create_index(op.f('ix_solutions_slug'), 'solutions', ['slug'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('authors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_authors_id'), 'authors', ['id'], unique=False)
    op.create_table('product_faqs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=True),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_faqs_id'), 'product_faqs', ['id'], unique=False)
    op.create_index(op.f('ix_product_faqs_sequence'), 'product_faqs', ['sequence'], unique=False)
    op.create_table('product_features',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=True),
    sa.Column('section_title', sa.Text(), nullable=True),
    sa.Column('section_subtitle', sa.Text(), nullable=True),
    sa.Column('tab_label', sa.Text(), nullable=True),
    sa.Column('content_title', sa.Text(), nullable=False),
    sa.Column('content_description', sa.Text(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('benefits', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('sequence', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_features_id'), 'product_features', ['id'], unique=False)
    op.create_index(op.f('ix_product_features_sequence'), 'product_features', ['sequence'], unique=False)
    op.create_table('product_social_trust_links',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=True),
    sa.Column('social_trust_id', sa.UUID(), nullable=True),
    sa.Column('sequence', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['social_trust_id'], ['social_trusts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_social_trust_links_id'), 'product_social_trust_links', ['id'], unique=False)
    op.create_index(op.f('ix_product_social_trust_links_sequence'), 'product_social_trust_links', ['sequence'], unique=False)
    op.create_table('product_why_us',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=True),
    sa.Column('section_title', sa.Text(), nullable=True),
    sa.Column('section_subtitle', sa.Text(), nullable=True),
    sa.Column('card_label', sa.Text(), nullable=True),
    sa.Column('icon', sa.String(), nullable=True),
    sa.Column('sequence', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_why_us_id'), 'product_why_us', ['id'], unique=False)
    op.create_index(op.f('ix_product_why_us_sequence'), 'product_why_us', ['sequence'], unique=False)
    op.create_table('service_competencies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('service_page_id', sa.UUID(), nullable=True),
    sa.Column('skill_name', sa.String(), nullable=False),
    sa.Column('percentage_value', sa.Integer(), nullable=False),
    sa.Column('rank_order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['service_page_id'], ['service_pages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_service_competencies_id'), 'service_competencies', ['id'], unique=False)
    op.create_index(op.f('ix_service_competencies_rank_order'), 'service_competencies', ['rank_order'], unique=False)
    op.create_table('service_focus_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('service_page_id', sa.UUID(), nullable=True),
    sa.Column('card_title', sa.Text(), nullable=False),
    sa.Column('card_desc', sa.Text(), nullable=True),
    sa.Column('icon_image', sa.String(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['service_page_id'], ['service_pages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_service_focus_items_display_order'), 'service_focus_items', ['display_order'], unique=False)
    op.create_index(op.f('ix_service_focus_items_id'), 'service_focus_items', ['id'], unique=False)
    op.create_table('service_methodologies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('service_page_id', sa.UUID(), nullable=True),
    sa.Column('phase_number', sa.String(), nullable=True),
    sa.Column('phase_title', sa.Text(), nullable=False),
    sa.Column('phase_desc', sa.Text(), nullable=True),
    sa.Column('icon_image', sa.String(), nullable=True),
    sa.Column('phase_order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['service_page_id'], ['service_pages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_service_methodologies_id'), 'service_methodologies', ['id'], unique=False)
    op.create_index(op.f('ix_service_methodologies_phase_order'), 'service_methodologies', ['phase_order'], unique=False)
    op.create_table('service_offerings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('service_page_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('checklist', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('icon_image', sa.String(), nullable=True),
    sa.Column('highlight_badge', sa.String(), nullable=True),
    sa.Column('button_text', sa.String(), nullable=True),
    sa.Column('button_url', sa.String(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['service_page_id'], ['service_pages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_service_offerings_display_order'), 'service_offerings', ['display_order'], unique=False)
    op.create_index(op.f('ix_service_offerings_id'), 'service_offerings', ['id'], unique=False)
    op.create_table('service_quick_steps',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('service_page_id', sa.UUID(), nullable=True),
    sa.Column('step_label', sa.String(), nullable=True),
    sa.Column('step_title', sa.Text(), nullable=False),
    sa.Column('step_desc', sa.Text(), nullable=True),
    sa.Column('checklist', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('step_order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['service_page_id'], ['service_pages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_service_quick_steps_id'), 'service_quick_steps', ['id'], unique=False)
    op.create_index(op.f('ix_service_quick_steps_step_order'), 'service_quick_steps', ['step_order'], unique=False)
    op.create_table('solution_faqs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('solution_id', sa.UUID(), nullable=True),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['solution_id'], ['solutions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_solution_faqs_id'), 'solution_faqs', ['id'], unique=False)
    op.create_index(op.f('ix_solution_faqs_sequence'), 'solution_faqs', ['sequence'], unique=False)
    op.create_table('solution_features',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('solution_id', sa.UUID(), nullable=True),
    sa.Column('tab_label', sa.String(), nullable=True),
    sa.Column('content_title', sa.String(), nullable=True),
    sa.Column('content_description', sa.Text(), nullable=True),
    sa.Column('benefits', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('sequence', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['solution_id'], ['solutions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_solution_features_id'), 'solution_features', ['id'], unique=False)
    op.create_index(op.f('ix_solution_features_sequence'), 'solution_features', ['sequence'], unique=False)
    op.create_table('solution_related_products',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('solution_id', sa.UUID(), nullable=True),
    sa.Column('product_id', sa.UUID(), nullable=True),
    sa.Column('icon_url', sa.String(), nullable=True),
    sa.Column('sequence', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['solution_id'], ['solutions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_solution_related_products_id'), 'solution_related_products', ['id'], unique=False)
    op.create_index(op.f('ix_solution_related_products_sequence'), 'solution_related_products', ['sequence'], unique=False)
    op.create_table('solution_social_trust_links',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('solution_id', sa.UUID(), nullable=True),
    sa.Column('social_trust_id', sa.UUID(), nullable=True),
    sa.Column('sequence', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['social_trust_id'], ['social_trusts.id'], ),
    sa.ForeignKeyConstraint(['solution_id'], ['solutions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_solution_social_trust_links_id'), 'solution_social_trust_links', ['id'], unique=False)
    op.create_index(op.f('ix_solution_social_trust_links_sequence'), 'solution_social_trust_links', ['sequence'], unique=False)
    op.create_table('solution_why_us',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('solution_id', sa.UUID(), nullable=True),
    sa.Column('section_type', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('icon', sa.String(), nullable=True),
    sa.Column('sequence', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['solution_id'], ['solutions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_solution_why_us_id'), 'solution_why_us', ['id'], unique=False)
    op.create_index(op.f('ix_solution_why_us_sequence'), 'solution_why_us', ['sequence'], unique=False)
    op.create_table('articles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('publisher_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['publisher_id'], ['authors.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    op.create_index(op.f('ix_articles_id'), 'articles', ['id'], unique=False)
    op.create_index(op.f('ix_articles_slug'), 'articles', ['slug'], unique=True)
    op.create_table('article_categories',
    sa.Column('article_id', sa.UUID(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('article_id', 'category_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('article_categories')
    op.drop_index(op.f('ix_articles_slug'), table_name='articles')
    op.drop_index(op.f('ix_articles_id'), table_name='articles')
    op.drop_table('articles')
    op.drop_index(op.f('ix_solution_why_us_sequence'), table_name='solution_why_us')
    op.drop_index(op.f('ix_solution_why_us_id'), table_name='solution_why_us')
    op.drop_table('solution_why_us')
    op.drop_index(op.f('ix_solution_social_trust_links_sequence'), table_name='solution_social_trust_links')
    op.drop_index(op.f('ix_solution_social_trust_links_id'), table_name='solution_social_trust_links')
    op.drop_table('solution_social_trust_links')
    op.drop_index(op.f('ix_solution_related_products_sequence'), table_name='solution_related_products')
    op.drop_index(op.f('ix_solution_related_products_id'), table_name='solution_related_products')
    op.drop_table('solution_related_products')
    op.drop_index(op.f('ix_solution_features_sequence'), table_name='solution_features')
    op.drop_index(op.f('ix_solution_features_id'), table_name='solution_features')
    op.drop_table('solution_features')
    op.drop_index(op.f('ix_solution_faqs_sequence'), table_name='solution_faqs')
    op.drop_index(op.f('ix_solution_faqs_id'), table_name='solution_faqs')
    op.drop_table('solution_faqs')
    op.drop_index(op.f('ix_service_quick_steps_step_order'), table_name='service_quick_steps')
    op.drop_index(op.f('ix_service_quick_steps_id'), table_name='service_quick_steps')
    op.drop_table('service_quick_steps')
    op.drop_index(op.f('ix_service_offerings_id'), table_name='service_offerings')
    op.drop_index(op.f('ix_service_offerings_display_order'), table_name='service_offerings')
    op.drop_table('service_offerings')
    op.drop_index(op.f('ix_service_methodologies_phase_order'), table_name='service_methodologies')
    op.drop_index(op.f('ix_service_methodologies_id'), table_name='service_methodologies')
    op.drop_table('service_methodologies')
    op.drop_index(op.f('ix_service_focus_items_id'), table_name='service_focus_items')
    op.drop_index(op.f('ix_service_focus_items_display_order'), table_name='service_focus_items')
    op.drop_table('service_focus_items')
    op.drop_index(op.f('ix_service_competencies_rank_order'), table_name='service_competencies')
    op.drop_index(op.f('ix_service_competencies_id'), table_name='service_competencies')
    op.drop_table('service_competencies')
    op.drop_index(op.f('ix_product_why_us_sequence'), table_name='product_why_us')
    op.drop_index(op.f('ix_product_why_us_id'), table_name='product_why_us')
    op.drop_table('product_why_us')
    op.drop_index(op.f('ix_product_social_trust_links_sequence'), table_name='product_social_trust_links')
    op.drop_index(op.f('ix_product_social_trust_links_id'), table_name='product_social_trust_links')
    op.drop_table('product_social_trust_links')
    op.drop_index(op.f('ix_product_features_sequence'), table_name='product_features')
    op.drop_index(op.f('ix_product_features_id'), table_name='product_features')
    op.drop_table('product_features')
    op.drop_index(op.f('ix_product_faqs_sequence'), table_name='product_faqs')
    op.drop_index(op.f('ix_product_faqs_id'), table_name='product_faqs')
    op.drop_table('product_faqs')
    op.drop_index(op.f('ix_authors_id'), table_name='authors')
    op.drop_table('authors')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_solutions_slug'), table_name='solutions')
    op.drop_index(op.f('ix_solutions_id'), table_name='solutions')
    op.drop_table('solutions')
    op.drop_index(op.f('ix_social_trusts_sequence'), table_name='social_trusts')
    op.drop_index(op.f('ix_social_trusts_id'), table_name='social_trusts')
    op.drop_table('social_trusts')
    op.drop_index(op.f('ix_service_pages_slug'), table_name='service_pages')
    op.drop_index(op.f('ix_service_pages_id'), table_name='service_pages')
    op.drop_table('service_pages')
    op.drop_index(op.f('ix_products_slug'), table_name='products')
    op.drop_index(op.f('ix_products_id'), table_name='products')
    op.drop_index(op.f('ix_products_category'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_categories_id'), table_name='categories')
    op.drop_table('categories')
    # ### end Alembic commands ###
