"""make layout_type nullable

Revision ID: 7227ed37c901
Revises: 45a9e5e68a03
Create Date: 2025-12-23 09:58:45.985463

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7227ed37c901'
down_revision: Union[str, Sequence[str], None] = '45a9e5e68a03'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'layout_type',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'layout_type',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
