"""refactor social trust to global table

Revision ID: 7cc32f3d9883
Revises: becf5ce9fd1b
Create Date: 2025-12-17 12:40:01.622690

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7cc32f3d9883'
down_revision: Union[str, Sequence[str], None] = 'becf5ce9fd1b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_product_social_trusts_id'), table_name='product_social_trusts')
    op.drop_index(op.f('ix_product_social_trusts_sequence'), table_name='product_social_trusts')
    op.drop_table('product_social_trusts')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_social_trusts',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('product_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('logo_url', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('sequence', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('product_social_trusts_product_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('product_social_trusts_pkey'))
    )
    op.create_index(op.f('ix_product_social_trusts_sequence'), 'product_social_trusts', ['sequence'], unique=False)
    op.create_index(op.f('ix_product_social_trusts_id'), 'product_social_trusts', ['id'], unique=False)
    # ### end Alembic commands ###
