"""add promo table

Revision ID: 818e4f6ffaf8
Revises: 1c8f74ae0f9c
Create Date: 2025-12-24 14:49:13.409077

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '818e4f6ffaf8'
down_revision: Union[str, Sequence[str], None] = '1c8f74ae0f9c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('promos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('subtitle', sa.Text(), nullable=True),
    sa.Column('cta_label', sa.String(), nullable=True),
    sa.Column('cta_link', sa.String(), nullable=True),
    sa.Column('promo_badge_line1', sa.String(), nullable=True),
    sa.Column('promo_badge_line2', sa.String(), nullable=True),
    sa.Column('promo_badge_label', sa.String(), nullable=True),
    sa.Column('features', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('idle_bg_color', sa.String(), nullable=True),
    sa.Column('scroll_bg_color', sa.String(), nullable=True),
    sa.Column('illustration_url', sa.String(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_promos_id'), 'promos', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_promos_id'), table_name='promos')
    op.drop_table('promos')
    # ### end Alembic commands ###
