"""add solution tables

Revision ID: 8297d17d6ce7
Revises: 683d4cbfdecd
Create Date: 2025-12-11 07:54:04.191660

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8297d17d6ce7'
down_revision: Union[str, Sequence[str], None] = '683d4cbfdecd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('solutions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('slug', sa.String(), nullable=True),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('hero_title', sa.Text(), nullable=False),
    sa.Column('hero_subtitle', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_solutions_id'), 'solutions', ['id'], unique=False)
    op.create_index(op.f('ix_solutions_slug'), 'solutions', ['slug'], unique=True)
    op.create_table('solution_faqs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('solution_id', sa.UUID(), nullable=True),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['solution_id'], ['solutions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_solution_faqs_id'), 'solution_faqs', ['id'], unique=False)
    op.create_index(op.f('ix_solution_faqs_sequence'), 'solution_faqs', ['sequence'], unique=False)
    op.create_table('solution_features',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('solution_id', sa.UUID(), nullable=True),
    sa.Column('tab_label', sa.String(), nullable=True),
    sa.Column('content_title', sa.String(), nullable=True),
    sa.Column('content_description', sa.Text(), nullable=True),
    sa.Column('benefits', sa.JSON(), nullable=True),
    sa.Column('sequence', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['solution_id'], ['solutions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_solution_features_id'), 'solution_features', ['id'], unique=False)
    op.create_index(op.f('ix_solution_features_sequence'), 'solution_features', ['sequence'], unique=False)
    op.create_table('solution_related_products',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('solution_id', sa.UUID(), nullable=True),
    sa.Column('product_id', sa.UUID(), nullable=True),
    sa.Column('sequence', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['solution_id'], ['solutions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_solution_related_products_id'), 'solution_related_products', ['id'], unique=False)
    op.create_index(op.f('ix_solution_related_products_sequence'), 'solution_related_products', ['sequence'], unique=False)
    op.create_table('solution_why_us',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('solution_id', sa.UUID(), nullable=True),
    sa.Column('section_type', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('icon', sa.String(), nullable=True),
    sa.Column('sequence', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['solution_id'], ['solutions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_solution_why_us_id'), 'solution_why_us', ['id'], unique=False)
    op.create_index(op.f('ix_solution_why_us_sequence'), 'solution_why_us', ['sequence'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_solution_why_us_sequence'), table_name='solution_why_us')
    op.drop_index(op.f('ix_solution_why_us_id'), table_name='solution_why_us')
    op.drop_table('solution_why_us')
    op.drop_index(op.f('ix_solution_related_products_sequence'), table_name='solution_related_products')
    op.drop_index(op.f('ix_solution_related_products_id'), table_name='solution_related_products')
    op.drop_table('solution_related_products')
    op.drop_index(op.f('ix_solution_features_sequence'), table_name='solution_features')
    op.drop_index(op.f('ix_solution_features_id'), table_name='solution_features')
    op.drop_table('solution_features')
    op.drop_index(op.f('ix_solution_faqs_sequence'), table_name='solution_faqs')
    op.drop_index(op.f('ix_solution_faqs_id'), table_name='solution_faqs')
    op.drop_table('solution_faqs')
    op.drop_index(op.f('ix_solutions_slug'), table_name='solutions')
    op.drop_index(op.f('ix_solutions_id'), table_name='solutions')
    op.drop_table('solutions')
    # ### end Alembic commands ###
