"""add product social trust link table

Revision ID: 8b205f7f71ae
Revises: 7cc32f3d9883
Create Date: 2025-12-17 12:48:55.978867

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b205f7f71ae'
down_revision: Union[str, Sequence[str], None] = '7cc32f3d9883'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('social_trusts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('logo_url', sa.String(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_social_trusts_id'), 'social_trusts', ['id'], unique=False)
    op.create_index(op.f('ix_social_trusts_sequence'), 'social_trusts', ['sequence'], unique=False)
    op.create_table('product_social_trust_links',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=True),
    sa.Column('social_trust_id', sa.UUID(), nullable=True),
    sa.Column('sequence', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['social_trust_id'], ['social_trusts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_social_trust_links_id'), 'product_social_trust_links', ['id'], unique=False)
    op.create_index(op.f('ix_product_social_trust_links_sequence'), 'product_social_trust_links', ['sequence'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_product_social_trust_links_sequence'), table_name='product_social_trust_links')
    op.drop_index(op.f('ix_product_social_trust_links_id'), table_name='product_social_trust_links')
    op.drop_table('product_social_trust_links')
    op.drop_index(op.f('ix_social_trusts_sequence'), table_name='social_trusts')
    op.drop_index(op.f('ix_social_trusts_id'), table_name='social_trusts')
    op.drop_table('social_trusts')
    # ### end Alembic commands ###
