"""add category column to products

Revision ID: 8d637bc411cd
Revises: 18e479cf7979
Create Date: 2025-12-02 09:30:50.332881

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8d637bc411cd'
down_revision: Union[str, Sequence[str], None] = '18e479cf7979'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('slug', sa.String(), nullable=True),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('hero_title', sa.Text(), nullable=False),
    sa.Column('hero_subtitle', sa.Text(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_category'), 'products', ['category'], unique=False)
    op.create_index(op.f('ix_products_id'), 'products', ['id'], unique=False)
    op.create_index(op.f('ix_products_slug'), 'products', ['slug'], unique=True)
    op.create_table('product_faqs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=True),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_faqs_id'), 'product_faqs', ['id'], unique=False)
    op.create_index(op.f('ix_product_faqs_sequence'), 'product_faqs', ['sequence'], unique=False)
    op.create_table('product_features',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=True),
    sa.Column('section_title', sa.Text(), nullable=True),
    sa.Column('section_subtitle', sa.Text(), nullable=True),
    sa.Column('tab_label', sa.Text(), nullable=False),
    sa.Column('content_title', sa.Text(), nullable=False),
    sa.Column('content_description', sa.Text(), nullable=True),
    sa.Column('benefits', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('sequence', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_features_id'), 'product_features', ['id'], unique=False)
    op.create_index(op.f('ix_product_features_sequence'), 'product_features', ['sequence'], unique=False)
    op.create_table('product_why_us',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=True),
    sa.Column('section_title', sa.Text(), nullable=True),
    sa.Column('section_subtitle', sa.Text(), nullable=True),
    sa.Column('card_label', sa.Text(), nullable=True),
    sa.Column('icon', sa.String(), nullable=True),
    sa.Column('sequence', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_why_us_id'), 'product_why_us', ['id'], unique=False)
    op.create_index(op.f('ix_product_why_us_sequence'), 'product_why_us', ['sequence'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_product_why_us_sequence'), table_name='product_why_us')
    op.drop_index(op.f('ix_product_why_us_id'), table_name='product_why_us')
    op.drop_table('product_why_us')
    op.drop_index(op.f('ix_product_features_sequence'), table_name='product_features')
    op.drop_index(op.f('ix_product_features_id'), table_name='product_features')
    op.drop_table('product_features')
    op.drop_index(op.f('ix_product_faqs_sequence'), table_name='product_faqs')
    op.drop_index(op.f('ix_product_faqs_id'), table_name='product_faqs')
    op.drop_table('product_faqs')
    op.drop_index(op.f('ix_products_slug'), table_name='products')
    op.drop_index(op.f('ix_products_id'), table_name='products')
    op.drop_index(op.f('ix_products_category'), table_name='products')
    op.drop_table('products')
    # ### end Alembic commands ###
