"""Refactor layanan

Revision ID: 9ac79dec9f3a
Revises: 49534f7cddca
Create Date: 2025-12-19 15:53:03.632594

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ac79dec9f3a'
down_revision: Union[str, Sequence[str], None] = '49534f7cddca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('service_pages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('slug', sa.String(), nullable=True),
    sa.Column('page_name', sa.Text(), nullable=False),
    sa.Column('hero_heading', sa.Text(), nullable=False),
    sa.Column('hero_tagline', sa.Text(), nullable=True),
    sa.Column('hero_bg_image', sa.String(), nullable=True),
    sa.Column('focus_section_heading', sa.Text(), nullable=True),
    sa.Column('focus_section_desc', sa.Text(), nullable=True),
    sa.Column('quick_step_heading', sa.Text(), nullable=True),
    sa.Column('quick_step_subheading', sa.Text(), nullable=True),
    sa.Column('methodology_heading', sa.Text(), nullable=True),
    sa.Column('methodology_desc', sa.Text(), nullable=True),
    sa.Column('competency_heading', sa.Text(), nullable=True),
    sa.Column('competency_desc', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_service_pages_id'), 'service_pages', ['id'], unique=False)
    op.create_index(op.f('ix_service_pages_slug'), 'service_pages', ['slug'], unique=True)
    op.create_table('service_competencies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('service_page_id', sa.UUID(), nullable=True),
    sa.Column('skill_name', sa.String(), nullable=False),
    sa.Column('percentage_value', sa.Integer(), nullable=False),
    sa.Column('rank_order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['service_page_id'], ['service_pages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_service_competencies_id'), 'service_competencies', ['id'], unique=False)
    op.create_index(op.f('ix_service_competencies_rank_order'), 'service_competencies', ['rank_order'], unique=False)
    op.create_table('service_focus_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('service_page_id', sa.UUID(), nullable=True),
    sa.Column('card_title', sa.Text(), nullable=False),
    sa.Column('card_desc', sa.Text(), nullable=True),
    sa.Column('icon_image', sa.String(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['service_page_id'], ['service_pages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_service_focus_items_display_order'), 'service_focus_items', ['display_order'], unique=False)
    op.create_index(op.f('ix_service_focus_items_id'), 'service_focus_items', ['id'], unique=False)
    op.create_table('service_methodologies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('service_page_id', sa.UUID(), nullable=True),
    sa.Column('phase_number', sa.String(), nullable=True),
    sa.Column('phase_title', sa.Text(), nullable=False),
    sa.Column('phase_desc', sa.Text(), nullable=True),
    sa.Column('phase_order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['service_page_id'], ['service_pages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_service_methodologies_id'), 'service_methodologies', ['id'], unique=False)
    op.create_index(op.f('ix_service_methodologies_phase_order'), 'service_methodologies', ['phase_order'], unique=False)
    op.create_table('service_quick_steps',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('service_page_id', sa.UUID(), nullable=True),
    sa.Column('step_label', sa.String(), nullable=True),
    sa.Column('step_title', sa.Text(), nullable=False),
    sa.Column('step_desc', sa.Text(), nullable=True),
    sa.Column('step_order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['service_page_id'], ['service_pages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_service_quick_steps_id'), 'service_quick_steps', ['id'], unique=False)
    op.create_index(op.f('ix_service_quick_steps_step_order'), 'service_quick_steps', ['step_order'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_service_quick_steps_step_order'), table_name='service_quick_steps')
    op.drop_index(op.f('ix_service_quick_steps_id'), table_name='service_quick_steps')
    op.drop_table('service_quick_steps')
    op.drop_index(op.f('ix_service_methodologies_phase_order'), table_name='service_methodologies')
    op.drop_index(op.f('ix_service_methodologies_id'), table_name='service_methodologies')
    op.drop_table('service_methodologies')
    op.drop_index(op.f('ix_service_focus_items_id'), table_name='service_focus_items')
    op.drop_index(op.f('ix_service_focus_items_display_order'), table_name='service_focus_items')
    op.drop_table('service_focus_items')
    op.drop_index(op.f('ix_service_competencies_rank_order'), table_name='service_competencies')
    op.drop_index(op.f('ix_service_competencies_id'), table_name='service_competencies')
    op.drop_table('service_competencies')
    op.drop_index(op.f('ix_service_pages_slug'), table_name='service_pages')
    op.drop_index(op.f('ix_service_pages_id'), table_name='service_pages')
    op.drop_table('service_pages')
    # ### end Alembic commands ###
