"""add service offerings and quick step footer

Revision ID: b74ea3fd2e15
Revises: 1ffee2ce1cae
Create Date: 2025-12-22 08:59:50.756354

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b74ea3fd2e15'
down_revision: Union[str, Sequence[str], None] = '1ffee2ce1cae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('service_offerings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('service_page_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('checklist', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('icon_image', sa.String(), nullable=True),
    sa.Column('highlight_badge', sa.String(), nullable=True),
    sa.Column('button_text', sa.String(), nullable=True),
    sa.Column('button_url', sa.String(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['service_page_id'], ['service_pages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_service_offerings_display_order'), 'service_offerings', ['display_order'], unique=False)
    op.create_index(op.f('ix_service_offerings_id'), 'service_offerings', ['id'], unique=False)
    op.add_column('service_pages', sa.Column('quick_step_footer', sa.Text(), nullable=True))
    op.add_column('service_pages', sa.Column('offering_heading', sa.Text(), nullable=True))
    op.add_column('service_pages', sa.Column('offering_desc', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('service_pages', 'offering_desc')
    op.drop_column('service_pages', 'offering_heading')
    op.drop_column('service_pages', 'quick_step_footer')
    op.drop_index(op.f('ix_service_offerings_id'), table_name='service_offerings')
    op.drop_index(op.f('ix_service_offerings_display_order'), table_name='service_offerings')
    op.drop_table('service_offerings')
    # ### end Alembic commands ###
