"""add product_social_trusts table

Revision ID: becf5ce9fd1b
Revises: 31109c1691fa
Create Date: 2025-12-17 09:20:21.261349

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'becf5ce9fd1b'
down_revision: Union[str, Sequence[str], None] = '31109c1691fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_social_trusts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('logo_url', sa.String(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_social_trusts_id'), 'product_social_trusts', ['id'], unique=False)
    op.create_index(op.f('ix_product_social_trusts_sequence'), 'product_social_trusts', ['sequence'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_product_social_trusts_sequence'), table_name='product_social_trusts')
    op.drop_index(op.f('ix_product_social_trusts_id'), table_name='product_social_trusts')
    op.drop_table('product_social_trusts')
    # ### end Alembic commands ###
