"""make layout_type nullable

Revision ID: c7e6c7a20613
Revises: 7227ed37c901
Create Date: 2025-12-23 10:25:07.420045

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c7e6c7a20613'
down_revision: Union[str, Sequence[str], None] = '7227ed37c901'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('service_pages', 'quick_step_layout',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('service_pages', 'methodology_layout',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('service_pages', 'methodology_layout',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('service_pages', 'quick_step_layout',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
