"""Solution db update

Revision ID: cec307dc3981
Revises: fb02ac05bdbe
Create Date: 2025-12-18 16:10:18.673666

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cec307dc3981'
down_revision: Union[str, Sequence[str], None] = 'fb02ac05bdbe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('solutions', sa.Column('core_solution_title', sa.String(), nullable=True))
    op.add_column('solutions', sa.Column('core_solution_subtitle', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('solutions', 'core_solution_subtitle')
    op.drop_column('solutions', 'core_solution_title')
    # ### end Alembic commands ###
