"""Solution update

Revision ID: fb02ac05bdbe
Revises: 809bfb276296
Create Date: 2025-12-18 14:58:55.962569

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb02ac05bdbe'
down_revision: Union[str, Sequence[str], None] = '809bfb276296'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('solution_related_products', sa.Column('icon_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('solution_related_products', 'icon_url')
    # ### end Alembic commands ###
