"""add methodology and competency footers

Revision ID: fec8faf81518
Revises: b74ea3fd2e15
Create Date: 2025-12-22 09:55:27.600989

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fec8faf81518'
down_revision: Union[str, Sequence[str], None] = 'b74ea3fd2e15'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service_pages', sa.Column('methodology_footer', sa.Text(), nullable=True))
    op.add_column('service_pages', sa.Column('competency_footer', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('service_pages', 'competency_footer')
    op.drop_column('service_pages', 'methodology_footer')
    # ### end Alembic commands ###
